export const FETCH_CONVERSATIONS_REQUEST = 'FETCH_CONVERSATIONS_REQUEST'
export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS'
export const FETCH_CONVERSATIONS_FAILURE = 'FETCH_CONVERSATIONS_FAILURE'
export const FETCH_CONVERSATION_BY_ID_REQUEST = 'FETCH_CONVERSATION_REQUEST'
export const FETCH_CONVERSATION_BY_ID_SUCCESS = 'FETCH_CONVERSATION_SUCCESS'
export const FETCH_CONVERSATION_BY_ID_FAILURE = 'FETCH_CONVERSATION_FAILURE'
export const SET_ACTIVE_CONVERSATION_ID = 'SET_ACTIVE_CONVERSATION_ID'
export const SET_ACTIVE_CONVERSATION = 'SET_ACTIVE_CONVERSATION'
export const CONVERSATIONS = 'CONVERSATIONS'
export const FETCH_ALL_LAST_MESSAGES_REQUEST = 'FETCH_ALL_LAST_MESSAGES_REQUEST'
export const FETCH_ALL_LAST_MESSAGES_SUCCESS = 'FETCH_ALL_LAST_MESSAGES_SUCCESS'
export const FETCH_ALL_LAST_MESSAGES_FAILURE = 'FETCH_ALL_LAST_MESSAGES_FAILURE'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE'
export const FETCH_MESSAGES_BY_CONVERSATION_ID_REQUEST = 'FETCH_MESSAGES_BY_CONVERSATION_ID_REQUEST'
export const FETCH_MESSAGES_BY_CONVERSATION_ID_SUCCESS = 'FETCH_MESSAGES_BY_CONVERSATION_ID_SUCCESS'
export const FETCH_MESSAGES_BY_CONVERSATION_ID_FAILURE = 'FETCH_MESSAGES_BY_CONVERSATION_ID_FAILURE'
export const SET_CHAT_MESSAGES = 'SET_CHAT_MESSAGES'
export const FETCH_MESSAGE_BY_ID = 'FETCH_MESSAGE_BY_ID'
export const SET_CHAT_FILE = 'SET_CHAT_FILE'
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS'
export const SET_CHAT_MESSAGES_PAGE = 'SET_CHAT_MESSAGES_PAGE'
export const SET_CHAT_MESSAGES_LIMIT = 'SET_CHAT_MESSAGES_LIMIT'
export const SET_CONVERSATIONS_PAGE = 'SET_CONVERSATIONS_PAGE'
export const SET_CONVERSATIONS_LIMIT = 'SET_CONVERSATIONS_LIMIT'
export const SET_TEXT_MESSAGE = 'SET_TEXT_MESSAGE'
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE'



export const ChatPlatform = {
    Whatsapp: 3,
    Instagram: 2, 
    Facebook: 1
};

export const ChatPlatformConverter = {
    3: 'Whatsapp',
    2: 'Instagram',
    1: 'Facebook'
};


export const MessageType = {
    Text: 1,
    Image: 2,
    File: 3,
    Video: 4
};