export const FETCH_CONTACT_BY_ID = 'FETCH_CONTACT_BY_ID';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAILED = 'API_FAILED'; 
export const RESET_WARNINGS = 'RESET_WARNINGS';